#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=50G
#SBATCH --partition=GPU
#SBATCH --gres=gpu:V100:1
#SBATCH -t 00:05:00
#SBATCH --job-name=self_attention_gpu

# Load the cuda module
module load cuda

# =======================================================
# Configurable parameters (override via environment)
# =======================================================
VERSION="${VERSION:-v1}"
# THREADS="${THREADS:-${SLURM_CPUS_PER_TASK}}"
BATCH="${BATCH:-2}"
N_HEADS="${N_HEADS:-8}"
# SEQ_LEN="${SEQ_LEN:-2048}"
SEQ_LEN="${SEQ_LEN:-1024}"
HEAD_DIM="${HEAD_DIM:-128}"

# Compile the code
make cuda VERSION=$VERSION

echo "Running GPU benchmark on Orfeo with UV"
OMP_PLACES=cores
OMP_PROC_BIND=close

if [ ! -d .venv ]; then
  echo "ERROR: .venv missing. Build environment before benchmarking."
  exit 1
fi

# 3. Activate the environment created by uv
source .venv/bin/activate

echo "=== Starting GPU benchmark ==="
# Check if torch sees the V100
python -c "import torch; print(f'Using Device: {torch.cuda.get_device_name(0)}')"


# Setup
# =======================================================
EXEC="./cmhsa.out"
ARGS="--batch ${BATCH} --n_heads ${N_HEADS} --seq_len ${SEQ_LEN} --head_dim ${HEAD_DIM} --threads 12 --warmup 3 --iters 5"
# ARGS="--batch ${BATCH} --n_heads ${N_HEADS} --seq_len ${SEQ_LEN} --head_dim ${HEAD_DIM} --threads ${THREADS}"

# Define the directory to store reports
report_dir_nsys="reports/nsys"
report_dir_ncu="reports/ncu"

# Create the directory if it doesn't exist
mkdir -p "$report_dir_nsys"
mkdir -p "$report_dir_ncu"

# Generate a unique report file name based on the current timestamp
timestamp=$(date +"%Y%m%d_%H%M%S")
report_file="report_${timestamp}"

# Run the nsys profile command and store the report in the specified directory
# nsys profile --trace=cuda --stats=true -o "${report_dir_nsys}/${report_file}" $EXEC $ARGS

# Notify the user
echo "Report generated: ${report_dir_nsys}/${report_file}.qdrep"

# Original
ncu --set full --launch-skip 0 --launch-count 1 --import-source yes -o "${report_dir_ncu}/${report_file}" $EXEC $ARGS
